"""empty message

Revision ID: 30daf577c8cc
Revises: a88185b48216
Create Date: 2021-12-27 16:47:41.928539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30daf577c8cc'
down_revision = 'a88185b48216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.drop_column('artists', 'seeking_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('artists', 'seeking_venue')
    # ### end Alembic commands ###
